### ISSUE TITLE
Unable to get commands error when using custom commands

### ISSUE THREAD

**Issue by jimbobbennett** [microsoft/Project-Santa-Cruz-Preview#101]
I'm trying to create a voice assistant. When I do I get an error popup in the Azure portal saying *Unable to get commands* and the **Command** dropdown shows *No custom commands found* despite me having custom commands.

If I try to refresh this list, I get the same error.

![Screenshot 2021-01-09 143126](https://user-images.githubusercontent.com/1710385/104109974-f63a2380-5287-11eb-894c-1ea38c61cdeb.png)

If I use the **Create new** option, it creates the command and populates this in the dropdown, but if I refresh the list or the page I get the same error and I'm unable to see the new command.

**Comment by jimbobbennett** [comment]
I also get the same error if I try to change the command the in device configuration.

![Screenshot 2021-01-09 143706](https://user-images.githubusercontent.com/1710385/104109990-30a3c080-5288-11eb-90c4-6d6baeee4a72.png)

**Comment by jimbobbennett** [comment]
The commands are all listed however from the *AI Projects->Speech* blade in the *Commands* tab.

![Screenshot 2021-01-09 144527](https://user-images.githubusercontent.com/1710385/104110131-65644780-5289-11eb-8dcb-7a580aa854fa.png)

**Comment by MS-Nikunja** [comment]
Hi @jimbobbennett , did you follow the steps in this link: https://github.com/microsoft/Project-Santa-Cruz-Preview/blob/main/user-guides/prototyping/how-tos/speech/voice-assistant-config.md? You can refer the steps mentioned under "**Commands configuration**. Let us know if you still get an error after following these steps.

**Comment by jimbobbennett** [comment]
Yes - I was following those steps.

**Comment by v-prsasa** [comment]
Hi @jimbobbennett  This bug is found in dog food environment. I was able to reproduce this now. It loads perfectly fine on portal.azure.com. Is there any restriction on dog-food? 

Looks like this bug environment is df. 

NoCommands.PNG
