### ISSUE TITLE
Enhancement request - make it easier to capture images

### ISSUE THREAD

**Issue by jimbobbennett** [microsoft/Project-Santa-Cruz-Preview#102]
Some enhancement suggestions to make it easier to capture images to train models:

* With the auto capture, provide some kind of feedback before and after the image is captured. For example, I used the 5 second capture of 25 images to capture a range of pictures of an item in a few positions, but some if them had my hand in the shot as I was moving the items being photographed. It would be easier if there was an indication before/after each shot was taken.
* Provide a way on the webstream video preview to remove the outlines from the objects detected by the model and add a button to capture an image and either download it for upload later, or send it to the custom vision project. That way it can be previewed before capturing.

**Comment by v-iskha** [comment]
@jimbobbennett - Thank you for sharing the feedback. Feature team are working on it and will do the needful.
