### ISSUE TITLE
Difference in model ratings between custom vision and santa cruz

### ISSUE THREAD

**Issue by jimbobbennett** [microsoft/Project-Santa-Cruz-Preview#103]
I've trained a model using images captured from my Santa Cruz device. When I look at the values for precision, recall and mAP in the Custom Vision portal and the Santa Cruz portal I get different results for recall - 100% vs 89%.

Not sure if this is an issue in the Santa Cruz portal or the Custom Vision portal.

**Custom Vision**

![Screenshot 2021-01-11 114545](https://user-images.githubusercontent.com/1710385/104230846-f7439000-5402-11eb-846f-1709e7a3577e.png)

**Santa Cruz**

![Screenshot 2021-01-11 114723](https://user-images.githubusercontent.com/1710385/104230880-01658e80-5403-11eb-96e2-6066269a2c84.png)

**Comment by elqu20** [comment]
I experienced the same issue as well.

**Comment by kalpesh94** [comment]
@ikhapova : Can you take a look?

**Comment by ikhapova** [comment]
@jimbobbennett Thank you for feedback. The fix is being developed.
