### ISSUE TITLE
No live stream with a deployed model.

### ISSUE THREAD

**Issue by jimbobbennett** [microsoft/Project-Santa-Cruz-Preview#104]
I've been working through the guide to deploy a custom vision model to my Santa Cruz device.

Whilst it's deploying I can see alive stream through the Webstream Video page, with text saying it's deploying the model, converting the model, loading the model etc.

Once deployed all I get is a black screen:

![Screenshot 2021-01-11 115333](https://user-images.githubusercontent.com/1710385/104231339-a7b19400-5403-11eb-88e2-317fc600e8f9.png)

I've tried rebooting the device and redeploying the model, but it stays as a black screen.

**Comment by XavierGeerinck** [comment]
I had the same issue, was due to an Assertion error that made the module exit too early

Could fix it here by plugging in the Eye board again and restarting the container through SSH

Error

```
inference: /eyesom/AzureEyeMX/project/shared/VPUAL/host/stubs/InferencePlg.cpp:267: void vpual::stub::Inference::pull_result(vpual::stub::Inference::FrameResult*) const: Assertion `packet && packet->length == sizeof(PlgXLinkOut_Header)' failed
```

**Comment by glogemann** [comment]
Same issue here :  looks like the AzureEye module crashes after a wihile (about 30sec.)
![image](https://user-images.githubusercontent.com/9800738/108844057-dcf0fa80-75db-11eb-9064-7d23a5094991.png)

![image](https://user-images.githubusercontent.com/9800738/108844330-45d87280-75dc-11eb-8856-4a6f438597a6.png)

![image](https://user-images.githubusercontent.com/9800738/108844589-99e35700-75dc-11eb-83cf-53500d977e8d.png)

**Comment by rploeg** [comment]
Running the latest firmware, but I also get a black screen (also after rebooting, unplug everything) when I try to see the webstream video. All my containers are running correctly: 

![image](https://user-images.githubusercontent.com/49752333/110097264-1de8cc00-7d9f-11eb-8e04-f1a7f316b6da.png)

**Comment by v-iskha** [comment]
@glogemann @jimbobbennett - If the runtime status of azureeyemodule is not listed as running, click Set modules -> azureeyemodule. On the Module Settings page, set Desired Status to running and click Update.

You can refer this [guide](https://github.com/microsoft/Project-Santa-Cruz-Preview/blob/main/user-guides/general/troubleshooting/vision_solution_troubleshooting.md#eye-module-troubleshooting-tips) for Eye module troubleshooting.

**Comment by v-iskha** [comment]
@jimbobbennett - Closing this issue as there is no further update since 9-Mar-21. Assuming the issue to be fixed.
