### ISSUE TITLE
no SD card in the devkit

### ISSUE THREAD

**Issue by ozhernan** [microsoft/Project-Santa-Cruz-Preview#105]
In https://github.com/microsoft/Project-Santa-Cruz-Preview/blob/main/user-guides/updating/usb_updating.md

In method #3 the doc says "remove the SD card" the devkit does include an SD card so this is not needed

DIP switches access is impossible without removingg the aluminum case. We need instructions to properly disassembly the dev kit without damaging the antennas cables

**Comment by elqu20** [comment]
Investigation in progress.

**Comment by elqu20** [comment]
Some early iterations of the devkit contained an SD card, but the vast majority of users have a newer iteration that does not contain a card. The documentation will be updated to reflect this.

**Comment by elqu20** [comment]
Closing this issue for now.

A separate internal investigation is in progress regarding the devkit disassembly. I will post an update when new documentation is live.
