### ISSUE TITLE
Cannot do USB update method #3: non-standard situations

### ISSUE THREAD

**Issue by Vivihung** [microsoft/Project-Santa-Cruz-Preview#112]
Following the steps of [this](https://github.com/microsoft/Project-Santa-Cruz-Preview/blob/7bee53f6d72ddb998d55db599cd972c5f22e9d5a/user-guides/updating/usb_updating.md#usb-update-method-3-non-standard-situations) document.

Note: I lost the root password, therefore USB update with no sudo command is my only option...

Hit two issues:
1. There is no SD card on the board (Known issue #105 ) => skip removing the SD card part
2. **The board doesn't boot into USB flash mode.**

My steps:
1. Unscrewed the board from the case and changed the DIP switches to 1011.
2. Connect my laptop (Windows) with the carrier board with USB-C cable. The carrier board is still powered-off.
3. Download the USB files from [here](https://projectsantacruz.microsoft.com/Download).
4. Unzip the raw.xz file by 7zip.
5. Make sure all the files (uuu.exe, .raw, fast-hab-fw.raw, emmc_full.txt) I need is under the same folder as the uuu.exe
6. Run the command
`uuu -b emmc_full.txt fast-hab-fw.raw pe101-uefi-1.0.20200916.1424.raw`
7. Power on the carrier board

Result:
The uuu tool is waiting for USB device forever
![image](https://user-images.githubusercontent.com/4814277/105260580-e271a580-5b42-11eb-8ec2-77a0d23ed1b7.png)

Expected result:
The uuu tool should do the magic once the board is turned on.

Could someone help please?

**Comment by elqu20** [comment]
@alexakesson-MSFT is there a workaround for this issue?

**Comment by alexakesson-MSFT** [comment]
@elqu20 Thank you for bringing this to our attention; this is a new issue. Investigation is ongoing. + @SillyKeith and @kalpesh94

**Comment by SillyKeith** [comment]
please set the dip switches to 0101 and see if it works for you.  There were HW & firmware revisions that we were not aware of that modified our previous methods.  Setting to 0101 is what our HW team said should work.  
Please report back 
Thx

**Comment by Vivihung** [comment]
Using DIP switch with 0101 works! Thank for the prompt help!
![image](https://user-images.githubusercontent.com/4814277/105557890-2808ac80-5cc2-11eb-8c7b-768192e5b2e3.png)

**Comment by SillyKeith** [comment]
glad to hear!  Don't forget to switch them back after the update finishes.
Toggle the DIP switches to eMMC boot mode (1001).
We'll update the docs.
