### ISSUE TITLE
Deployment information could not be retrieved

### ISSUE THREAD

**Issue by Neurotaur** [microsoft/Project-Santa-Cruz-Preview#114]
Error in Azure Portal when We try to list the Santa Cruz SDK IoT Devices
![AzurePortalError](https://user-images.githubusercontent.com/6352684/105391107-637e7a80-5bdf-11eb-8569-e61550fd76af.png)

**Comment by Neurotaur** [comment]
Related Notification: "undefined is not an object (evaluating 'n.responseObject.message')

**Comment by WendyAnn0079** [comment]
Hello - did you setup the device in ADU and go through OOBE?

**Comment by Neurotaur** [comment]
It is working fine right now. 
May be a problem in Azure Portal?

**Comment by WendyAnn0079** [comment]
@Neurotaur okay great, please let us know if you have see the problem again.
