### ISSUE TITLE
Doc improvement: Azure subscription setup failed with forbidden error

### ISSUE THREAD

**Issue by Vivihung** [microsoft/Project-Santa-Cruz-Preview#118]
This is a documentation improvement suggestion.

While [setup the Azure subscription](https://github.com/microsoft/Project-Santa-Cruz-Preview/blob/main/user-guides/getting_started/azure-subscription-onboarding.md) for Santa Cruz devkit, in the steps of DPS and ADU, it's good the wizard detects there are changes need to be made in the subscription level:
![image](https://user-images.githubusercontent.com/4814277/106499105-01dacd80-6475-11eb-93ab-c3f6619456f4.png)

However, I clicked on the Register "Microsoft.DeviceUpdate" and "PublicPreview" checkboxes and the UI returned a permission error:
![image](https://user-images.githubusercontent.com/4814277/106499643-ae1cb400-6475-11eb-9ff1-8f7dbbac1649.png)

Then I realize it's because I don't have the owner permission of the subscription.

Here is my suggestion:

- Add having Azure subscription owner permission as prerequisite in the [documentation](https://github.com/microsoft/Project-Santa-Cruz-Preview/blob/main/user-guides/getting_started/azure-subscription-onboarding.md). 

Thanks.

**Comment by v-iskha** [comment]
@elqu20 - Hi Elena, for your action. Thanks.

**Comment by elqu20** [comment]
Investigation in progress.

**Comment by elqu20** [comment]
Documentation has been updated.
