### ISSUE TITLE
Setup Azure subscription UI freeze if unchecked ADU 

### ISSUE THREAD

**Issue by Vivihung** [microsoft/Project-Santa-Cruz-Preview#119]
UX improvement suggestion.

Following [this](https://github.com/microsoft/Project-Santa-Cruz-Preview/blob/main/user-guides/getting_started/azure-subscription-onboarding.md) doc to setup Azure subscription for my Santa Cruz devkit.

Repro steps:

1. In the ADU step, **unchecked** the ADU checkbox and click on the "Next" button.
2. See two error messages on the AIU page: a) configure ADU error message in the UI, b) an application error in the bottom of the page - "An error has occurred. This application may no longer respond until reloaded."
![image](https://user-images.githubusercontent.com/4814277/106500345-8e39c000-6476-11eb-80b4-abdf13aa9c7c.png)

At this state, the AIU checkbox cannot be uncheck. The "Next" button is grey out.
I have to refresh the browser to get back to the ADU page.

Suggestions:

- If ADU is required to be configured, please remove the checkbox. The checkbox sends a message that the step can be skip but leads to an error.
- Having a "Previous" button to help user go back to the previous step to change configuration.

Thanks.

**Comment by v-iskha** [comment]
@Vivihung - This is to inform you that Azure Subscription is no longer needed to use the DevKit. Hence closing this issue.
