### ISSUE TITLE
Custom vision model got reverted to the built-in one if power off the device

### ISSUE THREAD

**Issue by Vivihung** [microsoft/Project-Santa-Cruz-Preview#120]
I'm not sure it's by design or it's a bug.
But I found the custom vision model I deployed to the Azure Eye is reverted to the built-in one after I power off the Santa Cruz. 
The custom model is trained and deployed to the device via Custom Vision website.
I power off the Santa Cruz kit by pressing the power button on the side of the carrier board. Once the lights on the device are off, I unplug the power cable from the outlet.

I have tested it 2 times and it has the consistent behavior -  rolling back to the built-in model.

Is this expected or a bug?

**Comment by mimcco** [comment]
@tsampige - can you take a look?

**Comment by v-iskha** [comment]
@Vivihung - Just checking the status on this issue. Also have you tried this [DiagTool](https://github.com/microsoft/Project-Santa-Cruz-Preview/blob/main/tools/DiagTool/diagtool_guide.md#diagtool-user-guide) to run the diagnostics.

**Comment by tsampige** [comment]
@ikhapova can you have someone investigate this issue?

**Comment by Vivihung** [comment]
@v-iskha, I can repro it every time I power off the device. (long press the power button on the SBC)
I haven't run the DiagTool. With what steps should I run the DiagTool? Turn on the kit and run it directly?

**Comment by v-iskha** [comment]
@Vivihung - You can connect your devkit components and power on the carrier board. If your devkit is not connected to a Wi-Fi network (which is set up through OOBE) or a network over Ethernet, connect to your devkit's SoftAP hotspot. 
You can refer the full guide [here](https://github.com/microsoft/Project-Santa-Cruz-Preview/blob/main/tools/DiagTool/diagtool_guide.md#diagtool-user-guide)

**Comment by v-iskha** [comment]
@Vivihung - Any progress.

**Comment by tsampige** [comment]
@Vivihung Also once the device is booted, does the default model switches back to the sample one that you had deployed originally?

**Comment by Vivihung** [comment]
@tsampige, no. The model it falls back to, is the default model installed in the Eye.
I don't know if the default model has been installed in the device since factory; or it is installed when we connect the kit to Azure. But the model is not built by me for sure. It can recognize objects (chair, cat, desk, bed, .... etc) already.

**Comment by v-iskha** [comment]
@Vivihung - Yes, the default model is the factory installed (also known as sample modules). Default module should recognize basic devices like chair, desk, bed, etc.
There is already a bug identified for custom vision. Dev team has fixed the issue and the fix will be released in the upcoming software update. Hence closing this issue. Please update the device once the new software update is available.
