### ISSUE TITLE
Device completely broken after firmware update

### ISSUE THREAD

**Issue by balakreshnan** [microsoft/Project-Santa-Cruz-Preview#135]
Hi All,

I downloaded the latest firmware and updated using USB cable and followed the https://github.com/microsoft/Project-Santa-Cruz-Preview/blob/main/user-guides/updating/usb_updating.md. After upload is completed i removed the power and then disconnected the USC C cable and power back the device and now i see the lights not cannot see SoftAP wireless nor the device is connected to my wifi any more. So now i cannot connect to the device.

here is the version: pe101-uefi-1.0.20210208.0637.raw

Previous version:
"swVersion": {
          "value": "2020.108.101.105"
        },

**Comment by v-iskha** [comment]
@kalpesh94 - Could you please look into this issue. Thanks.

**Comment by mikelor** [comment]
@balakreshnan take a look at my issue #139

I've got it somewhat recovered after updating to the latest firmware.

**Comment by kalpesh94** [comment]
@balakreshnan : Is the device recovered?

**Comment by v-iskha** [comment]
@mikelor - Any updates on the device after it got recovered.

**Comment by mikelor** [comment]
Well, I never really got it back to where LED 02 Would get to a solid green. It either continues to flash green or turns off.

The IoTHub shows it as connected and I can run the video stream and and the automotive speech sample.

Working on a custom application now following the advanced tutorial.

Waiting also for the next firmware update.

**Comment by v-iskha** [comment]
@mikelor - Thank you for sharing the feedback. Much appreciated. The next software update will surely be bug free (known bugs) and more stable. Since we do not have any further troubleshooting on this we will be closing this issue.
