### ISSUE TITLE
Feature Request - Project Santa Cruz Portal / Remove Old Santa Cruz Instances from Drop Down

### ISSUE THREAD

**Issue by mikelor** [microsoft/Project-Santa-Cruz-Preview#137]
The current version of the [Project Santa Cruz Portal](https://projectsantacruz.microsoft.com/) does not allow the ability to "remove" an instance, even if the resources and resource group have been deleted in the portal.

Why is this useful: I've stepped through initializing my devkit multiple times in an effort to automate as much as possible, however, these old instances still show up in the portal, even though I have deleted all resources associated with the instance.

Please add the ability to remove these instances, or remove them automagically if the resource group is no longer available in the subscription.

**Comment by v-iskha** [comment]
@tsampige - It looks like feature enhancement request.

**Comment by v-iskha** [comment]
@ikhapova - Could you please have a look into this. The current version of the Project Santa Cruz Portal does not allow the ability to "remove" an instance, even if the resources and resource group have been deleted in the portal.

**Comment by mimcco** [comment]
@mikelor thanks for this feedback. The good news is that we no longer require users to go through this portal to configure their Azure environment. You should be able to proceed with using the dev kit. Let us know if you experience any other issues.

**Comment by mikelor** [comment]
Thanks @mimcco
Maybe I'm missing something, but how do we add Azure Device Update (ADU) to our IoTHub? This was done via the portal. When I look at "Device Updates" in the header, it points to a link [Account Settings](https://projectsantacruz.microsoft.com/Summary)

So is ADU configured another way? Given that I can't do this via ARM (See #138), I don't see any other way to do this except via the portal. :)

![image](https://user-images.githubusercontent.com/341942/108890203-20d70600-75c2-11eb-81e0-c5081bfe587b.png)
