### ISSUE TITLE
Feature Request - Support for Automation / ARM Templates / Deployment Scripts

### ISSUE THREAD

**Issue by mikelor** [microsoft/Project-Santa-Cruz-Preview#138]
I'm attempting to automate the setup for an instance of a Santa Cruz environment as much as possible utilizing Project Bicep and the Azure Cli. 

So far, I've been able to automate the IoT Hub and ProvisioningServices resources but have hit a snag with the "Device Update for IoT Hub" resource. When I attempt to "Export the Template", I get an error. Most likely due to this service still being in private preview.

However, this would speed up the creation of new Santa Cruz environments for development and testing environments significantly. For the current state of this automation  see the "azure/moclips.qa.bicep" file in the ["moclips](https://github.com/mikelor/moclips)" repository.

**Comment by v-iskha** [comment]
@tsampige - This also looks like feature enhancement request.

**Comment by mimcco** [comment]
Hi @mikelor the Azure Device Update service is still in "private preview" so it is expected that you would have trouble accessing it directly. It is for this reason we stood up the onboarding portal, as a way to  add the Update Service to IoTHubs. We expect the Update service to be public soon. We will let you know when it is available.
