### ISSUE TITLE
During onboarding, failing on "Create IoT Hub" with Microsoft employee account. 

### ISSUE THREAD

**Issue by KijoKim76** [microsoft/Project-Santa-Cruz-Preview#142]
Hi 

I have got an issue "internal server error has occurred while creating a new Iot Hub." on Create IoT Hub phase. Do we have any server side error? 

![image](https://user-images.githubusercontent.com/20589866/108792312-4fee7700-75c4-11eb-9de4-a92ba8f5c422.png)

**Comment by MS-Nikunja** [comment]
Hi @KijoKim76, We just got an update that “onboarding of Azure subscription” is no longer needed to use the Dev Kit. Visit https://github.com/microsoft/Project-Santa-Cruz-Preview for any updates on Santa Cruz device.

**Comment by v-iskha** [comment]
Closing as per comment from Nikunja
