### ISSUE TITLE
Santa Cruz Portal - Updating Eye/Ear SOM Firmware - What Version?

### ISSUE THREAD

**Issue by mikelor** [microsoft/Project-Santa-Cruz-Preview#143]
I'm using the the [Santa Cruz Portal](https://projectsantacruz.microsoft.com) to update the Eye/Ear SOM Firmware. However when I go to select which version to update to it's unclear. Is it 9, 10, or 100. :)

See screenshot below for current experience.

![image](https://user-images.githubusercontent.com/341942/108869285-e5c9d800-75ab-11eb-85c1-0bfde0709bf3.png)

**Comment by v-prsasa** [comment]
@kalpesh94 Could you please look into this issue. Thanks.

**Comment by v-prsasa** [comment]
@EthanChangAED Could you please look into this?

**Comment by mikelor** [comment]
Just bumping this. Seems like an easy answer. What's the latest version for Ear and Eye SOM...

**Comment by v-iskha** [comment]
@mikelor - Just an update, we are working on an upgrade package that includes the public image plus updated firmware and step-by-step instructions on how to upgrade. We will revert back once it is available.

**Comment by v-iskha** [comment]
@mikelor - Since we are no longer using the Santa Cruz portal (no further updates will be available in future on this portal), we will be closing this issue.
