### ISSUE TITLE
Failing to setup ADU

### ISSUE THREAD

**Issue by kirk-marple** [microsoft/Project-Santa-Cruz-Preview#144]
I'm running into this same issue creating ADU account:
[Similar Issue](https://github.com/microsoft/Project-Santa-Cruz-Preview/issues/78)

I've made sure I'm an owner role in the subscription.  I've unregistered and re-registered Microsoft.DeviceUpdates resource provider, and run the REST API command to enable PublicPreview.

Pretty stumped right now on what to do next...?

**Comment by v-iskha** [comment]
@kirk-marple - We no longer require users to go through "Santa Cruz Private Preview" portal to configure their Azure environment. You should be able to proceed with using the dev kit. Let us know if you experience any other issues.

**Comment by kirk-marple** [comment]
Thanks - and maybe I just didn't wait long enough, just tried it again and it worked :)  Closing this issue.
