### ISSUE TITLE
Strange behavior of the two dev kits i received today  

### ISSUE THREAD

**Issue by glogemann** [microsoft/Project-Santa-Cruz-Preview#145]
Currently i'm facing an issue that the two devices i received today are not behaving as described in the documentation. 
on both devices the LED's on the compute unit are constantly off. only the power button is illuminated when the device is running 

SOFT AP seems to be working and OOBE works as well so it deploys and configures IOT Edge with the right names correctly but i got different results. on one device the azureeyemodule stops working with Errorcode 139 and no live video stream is visible in the portal
on the other device the OOBE never completes but the IOT Edge device is actually correctly initialized in the Azure portal. However the azureeyemodule got never initalized and started 

I was trying to do a firmware update to those devices but i was not able to perform this either through OTA nor through USB.

any body seen this as well with devices that send directly from china?

**Comment by kalpesh94** [comment]
@glogemann : What is the specific error message for update. @alexakesson-MSFT, fyi.

**Comment by v-iskha** [comment]
@glogemann - Looking for updates on the devices from your end.

**Comment by mikelor** [comment]
@glogemann what image version are you running on your devkit. I'm unable to update my image. You can view the image version by logging in w/SSH and typing
`cat /etc/adu-version`

**Comment by v-iskha** [comment]
@samecchang - On both Santa Cruz Private preview devices the LED's on the compute unit are constantly OFF. Only the power button is illuminated when the device is running. Could you please advise.

**Comment by samecchang** [comment]
I want to echo @mikelor's comment. The image version is important for us to identify the issue.

@glogemann would you please provide the image version information you are using? You can view the image version by logging in w/SSH and typing
cat /etc/adu-version

**Comment by v-iskha** [comment]
@glogemann - Just following up. Any update on finding the image version from the devices?

**Comment by v-iskha** [comment]
Closing this as the software bug is fixed in coming release.

**Comment by v-iskha** [comment]
@glogemann - We are pleased to announce the release of public software update today. Please [visit this](https://github.com/microsoft/Azure-Percept-Private-Preview#welcome-to-the-azure-percept-private-preview-github-page) page to update your dev kit's software and firmware today. It includes instructions as well.
You can also attend a drop-in call to get direct support. [Click here](https://github.com/microsoft/Azure-Percept-Private-Preview/blob/main/update-your-devkit-today/support-sessions.md) to see the schedule of calls or contact our team at aedppsup@microsoft.com
