### ISSUE TITLE
Telemetry message coming from Eye is missing content type and encoding

### ISSUE THREAD

**Issue by bgulseren** [microsoft/Project-Santa-Cruz-Preview#146]
I am experimenting with Santa Cruz Eye and trying to get the object detection data passed into a Digital Twin. In the Azure IoT Explorer, the telemetry message I am receiving from Santa Cruz Eye is including object/face detected in the body properly, as below.

```
{
  "body": [
    {
      "width": "95",
      "height": "107",
      "position_x": "433",
      "position_y": "282",
      "label": "face",
      "confidence": "0.953125",
      "timestamp": "1614286551645224683"
    }
  ],
  "enqueuedTime": "2021-02-25T20:55:51.122Z",
  "systemProperties": {
    "iothub-connection-device-id": "IoT-Edge-SantaCruz-BG",
    "iothub-connection-module-id": "azureeyemodule",
    "iothub-connection-auth-method": "{\"scope\":\"module\",\"type\":\"sas\",\"issuer\":\"iothub\",\"acceptingIpFilterRule\":null}",
    "iothub-connection-auth-generation-id": "...",
    "iothub-enqueuedtime": 1614286551091,
    "iothub-message-source": "Telemetry",
    "x-opt-sequence-number": 55066,
    "x-opt-offset": "33029376",
    "x-opt-enqueued-time": 1614286551122
  }
}
```

However, when using the Azure function to process the same body data coming from Eye, it comes in Base64 and needs to be decoded. I believe this is because the telemetry message received does not include important system properties, such as `systemProperties.iothub-content-type` and `systemProperties.iothub-content-encoding` like below.

```
 "systemProperties":{
    "iothub-content-type":"application/json",
    "iothub-content-encoding":"utf-8",
```

It is possible to decode the body string in Azure function, however I just wanted to bring this up in case it might be an unintended issue.

**Comment by v-iskha** [comment]
@bgulseren - Thank you for sharing the feedback. Feature team are working on it and will do the needful.
