### ISSUE TITLE
ssh remot login account creation fail 

### ISSUE THREAD

**Issue by KijoKim76** [microsoft/Project-Santa-Cruz-Preview#147]
why this is failed? I could completed setup by skipping but like to know why it fails

"Command failed:...... PAM: Authentication token is no longer valid: new one required" 

![image](https://user-images.githubusercontent.com/20589866/109248214-ba9fec80-7828-11eb-9763-58ea7f2acb1b.png)

**Comment by v-iskha** [comment]
@KijoKim76 - Please go to the root login and change the password. Once the root password is changed you will be able to change the SSH password.

To recover your user profiles, preform these steps after the OTA update:
[SSH into your devkit](https://github.com/microsoft/Project-Santa-Cruz-Preview/blob/main/user-guides/general/troubleshooting/ssh_and_serial_connection_setup.md) using “root” as the username. If you disabled the SSH “root” user login via OOBE, you must re-enable it. 

Run this command after successfully connecting:
mkdir -p /var/custom-configs/home; chmod 755 /var/custom-configs/home

To recover previous user home data, run the following command:
mkdir -p /tmp/prev-rootfs && mount /dev/mmcblk0p3 /tmp/prev-rootfs && [ ! -L /tmp/prev-rootfs/home ] && cp -a /tmp/prev-rootfs/home/* /var/custom-configs/home/. && echo "User home migrated!"; umount /tmp/prev-rootfs


Note: For known issues refer this [link](https://github.com/microsoft/Project-Santa-Cruz-Preview/blob/main/release-notes/known-issues.md).

**Comment by v-iskha** [comment]
Closing as known issue.
