### ISSUE TITLE
Azure Free Subscription will also works 

### ISSUE THREAD

**Issue by KijoKim76** [microsoft/Project-Santa-Cruz-Preview#152]
Hi, I have got that onboarding phase is no longer necessary for devkit OOBE. 
However, I'm wondering partners can proceed OOBE with free Azure account?

**Comment by mikelor** [comment]
@KijoKim76 I was just able to use my MSDN account that was never originally registered for the preview and it worked. So it's worth a try.

I created an Azure Template / Deploy Script for setting up the Azure Environment to make it really easy to spin up Azure Environments for testing. See https://github.com/mikelor/moclips

**Comment by v-iskha** [comment]
@KijoKim76 - Yes, you can use a free Azure account. Please refer this [link](https://azure.microsoft.com/en-us/free/) to create your Azure free Account today.
