### ISSUE TITLE
Is this repo going to be maintained going ahead?

### ISSUE THREAD

**Issue by amarrmb** [microsoft/Project-Santa-Cruz-Preview#155]
With the recent Azure percept announcement, is this repo going to be maintained going ahead or getting renamed into a more formal repo, or continuing to provide alpha/preview functionality?
Just want to understand the difference between this & other percept github repo like: https://github.com/microsoft/azure-percept-advanced-development

For someone who had access to the devkits and now also the new kits (via store), this is little confusing which repo to use.

**Comment by v-iskha** [comment]
@amarrmb - Yes this repo will continue to be active. 

On the other hand the "Azure-Percept-Advanced-Development" repository should be considered to be in preview/beta. Significant portions of these experiences are subject to change without warning. No part of this code should be considered stable.
