### ISSUE TITLE
Error creating DPS from https://projectsantacruz.microsoft.com/

### ISSUE THREAD

**Issue by dfcarpenter** [microsoft/Project-Santa-Cruz-Preview#156]
Here is the error message from my subscription's activity log JSON

`
 "{\"error\":{\"code\":\"HttpRequestPayloadAPISpecValidationFailed\",\"target\":\"Microsoft.DeviceUpdate/accounts/SCZd78aee32Adu680061/instances/SCZd78aee32AduInstance680061\",\"message\":\"HTTP request payload failed validation against API specification with one or more errors. Please see details for more information.\",\"details\":[{\"code\":\"ObjectAdditionalProperties\",\"message\":\"Additional properties not allowed: name. Paths in payload: '$.properties.iotHubs[0].name'\"}]}}"
`

**Comment by v-iskha** [comment]
@dfcarpenter - Santa Cruz [portal](https://projectsantacruz.microsoft.com/) is no longer needed. So you might face some issues with the portal as well. For any guidance or support you can refer official Santa Cruz [GitHub](https://github.com/microsoft/Project-Santa-Cruz-Preview#welcome-to-the-project-santa-cruz-private-preview) channel.
