### ISSUE TITLE
eye module work with custom vision

### ISSUE THREAD

**Issue by LiangJy123** [microsoft/Project-Santa-Cruz-Preview#157]
Hi , 
I have a question that after deploying the AI model on the eye module , I can't see the new result from the websteam video.
The websteam video is still showing the default evaluation.

I check the module twin and eye module logs , but  can't find any reaction when I deploy the AI model on eye module using the Azure Percept studio.

Can you offer some suggestions on how to troubleshoot this problem?

**Comment by v-prsasa** [comment]
@LiangJy123 You can go through this link for troubleshooting this problem-https://docs.microsoft.com/en-us/azure/azure-percept/troubleshoot-dev-kit.

**Comment by v-iskha** [comment]
@LiangJy123 - This is to let you know that Dev team has identified a bug in custom vision deployment. They are working to fix the bug at earliest. We will update you once the bug is fixed.

**Comment by LiangJy123** [comment]
Hi @v-iskha , Thank you for your reply. 
Before your reply , I was worried that something wrong with my setup and I tried many times.
Now I can concentrate on waiting for your good news.

**Comment by ecnochx** [comment]
I am having the very same issue deploying customer vision models. they simply won't seem to be loaded by the Eye SoM

**Comment by mar1a** [comment]
I am also facing the same issue. I exported the custom vision model as zip file using Vision AI Dev Kit and updated the ModelZipUrl in device twin property by referring this link https://github.com/microsoft/Project-Santa-Cruz-Preview/blob/main/user-guides/prototyping/containers/eye_module_overview.m,. still i could see the default AI model inferences in telemetry.

**Comment by tsampige** [comment]
The model file format for vision ai devkit (qualcomm based chipset) is different than the Azure Percept DK (Intel based chipset). The model exported using Vision AI dev kit won't run on the Azure Percept dk.

**Comment by ecnochx** [comment]
What about exporting the model as either ONNX or DockerFile (Linux), one of those should work with the Azure Percept DK right?

**Comment by mar1a** [comment]
> The model file format for vision ai devkit (qualcomm based chipset) is different than the Azure Percept DK (Intel based chipset). The model exported using Vision AI dev kit won't run on the Azure Percept dk.

Ok, Thanks for the confirmation.

**Comment by v-iskha** [comment]
@LiangJy123 - Closing this case as the custom vision bug is fixed in the new software update. We just need to wait for the new software update to be available publicly.

**Comment by v-iskha** [comment]
@LiangJy123 - We are pleased to announce the release of public software update today. Please [visit this](https://github.com/microsoft/Azure-Percept-Private-Preview#welcome-to-the-azure-percept-private-preview-github-page) page to update your dev kit's software and firmware today. It includes instructions as well.

You can also attend a drop-in call to get direct support. [Click here](https://github.com/microsoft/Azure-Percept-Private-Preview/blob/main/update-your-devkit-today/support-sessions.md) to see the schedule of calls or contact our team at aedppsup@microsoft.com
