### ISSUE TITLE
Error calling Create module ImageCapturingModule

### ISSUE THREAD

**Issue by Neurotaur** [microsoft/Project-Santa-Cruz-Preview#159]
Hi,
I get the follogin error in my device.

`{
  "body": {
    "version": 203,
    "properties": {
      "reported": {
        "lastDesiredVersion": 48,
        "lastDesiredStatus": {
          "code": 500,
          "description": "One or more errors occurred. (Error calling Create module ImageCapturingModule: Could not create module ImageCapturingModule\n\tcaused by: Could not create module ImageCapturingModule\n\tcaused by: error creating overlay mount to /var/lib/docker/overlay2/15d0813ac698ab11a3973aef32b74c9bbf3b2ed69c4ab4e459deb63216abfdbb-init/merged: too many levels of symbolic links)"
        },
        "$metadata": {
          "$lastUpdated": "2021-03-11T17:40:53.253854Z",
          "lastDesiredVersion": {
            "$lastUpdated": "2021-03-11T17:40:53.253854Z"
          },
          "lastDesiredStatus": {
            "$lastUpdated": "2021-03-11T17:40:53.253854Z",
            "code": {
              "$lastUpdated": "2021-03-11T17:40:53.253854Z"
            },
            "description": {
              "$lastUpdated": "2021-03-11T17:40:53.253854Z"
            }
          }
        },
        "$version": 155
      }
    }
  },
  "enqueuedTime": "2021-03-11T17:40:53.420Z",
  "properties": {
    "hubName": "santacruz-ant101",
    "deviceId": "ant105",
    "operationTimestamp": "2021-03-11T17:40:53.2538540+00:00",
    "moduleId": "$edgeAgent",
    "iothub-message-schema": "twinChangeNotification",
    "opType": "updateTwin"
  }
}`

![image](https://user-images.githubusercontent.com/6352684/110831227-a19f2e80-825f-11eb-8840-96b19591cc4f.png)

**Comment by v-iskha** [comment]
@tsampige - Please advice if you can help here. User is getting error 406 under IoT Edge Runtime. Module "ImageCapturingModule" is not running.

**Comment by tsampige** [comment]
@v-iskha could you ask the user to reboot the device and then try to re-deploy sample vision model from the Azure percept studio? The imagecapturemodule will get re-deployed which hopefully should address the issue.

**Comment by v-iskha** [comment]
@Neurotaur - As suggested, could you reboot the device and then try to re-deploy sample vision model from the Azure percept studio? The imagecapturemodule will get re-deployed which hopefully should address the issue. Let us know your observation.

**Comment by Neurotaur** [comment]
I uninstaled the ImageCapture Module. Now, I need directions to reinstall it.

![image](https://user-images.githubusercontent.com/6352684/110869304-c7dcc280-828f-11eb-89c7-453f2b980219.png)

**Comment by tsampige** [comment]
can you re-deploy sample vision model from the azure percept studio? The imagecapturemodule gets redeployed as part of the sample model deployment. Give 5-10mins to ensure that the sample model and the imagecapture module is getting deployed to the device.

**Comment by Neurotaur** [comment]
I get "Deployment error .Deployment was unsuccessful. Please try again."

![image](https://user-images.githubusercontent.com/6352684/110976203-3cfad700-8326-11eb-9b87-a3f12ba98dce.png)

![image](https://user-images.githubusercontent.com/6352684/110976070-1341b000-8326-11eb-9f1a-6888bc9b57be.png)

**Comment by v-iskha** [comment]
@Neurotaur - Could you please ensure the USB connection between the carrier board and the Eye SoM is connected properly. Also make sure you are using a usb-c to usb-c cable.

**Comment by Neurotaur** [comment]
I think Eye SoM is connected properly. I can see the webstream video from the carrier board.

![image](https://user-images.githubusercontent.com/6352684/110986267-13947800-8333-11eb-80b7-a9729b304b3c.png)

**Comment by v-iskha** [comment]
@Neurotaur - Thank you for the confirmation. Could you please share the device logs for investigatation.

You can share the logs generated from the following commands?
sudo docker logs azureeyemodule > azureeyemodule.log
sudo docker logs edgeAgent >edgeAgent.log

**Comment by Neurotaur** [comment]
[azureeyemodule.log](https://github.com/microsoft/Project-Santa-Cruz-Preview/files/6132525/azureeyemodule.log)
[edgeAgent.log](https://github.com/microsoft/Project-Santa-Cruz-Preview/files/6132526/edgeAgent.log)

**Comment by v-iskha** [comment]
@Neurotaur - Thank you for sharing the logs. From the logs I see the Azure application seems to be started/loaded before the device network connectivity is ready (dns not yet working and connections can't be opened), it can get stuck and may never connect even with unlimited time and retries. 

Try this, close all the application including Azure application, reboot the device. Once rebooted, wait for 5 mins so that the device gets stable. Start the azure application and try again. Let me the outcome.

**Comment by Neurotaur** [comment]
(1) I close all the applications. 
(2) I restarted the device
(3) I waited 5 minutes. 
(4) I deployed a Sample Vision Model from Azure Percept Studio

I get the same error: "Depoyment error. Deployment was unsuccessful. Please try again."

![image](https://user-images.githubusercontent.com/6352684/111000066-02edfd00-8347-11eb-89a5-8823ee934fc5.png)

**Comment by v-iskha** [comment]
@tsampige - Need your expertise here. Fabian is not able to deploy sample vision model from Azure Percept Studio. He has also shared the logs in earlier thread.

**Comment by v-iskha** [comment]
@MaxStrange - Need your expertise here. Fabian is not able to deploy sample vision model from Azure Percept Studio. He has also shared the logs in earlier thread.

**Comment by Neurotaur** [comment]
Hi,
Some news?

**Comment by v-iskha** [comment]
@Neurotaur - There is an update in azuremodule which you can upgrade by performing below steps

Go to IoT Hub -> IoT Edge -> Select Device -> click on Set Modules -> select azureyemodule, 
then change image uri to mcr.microsoft.com/azureedgedevices/azureeyemodule:2103-2 
and click update -> click on Review + create -> click on create. 

The module download will get initiated. To verify if the download is completed, click on Azureeyemodule and check if the reported value is same as desired value.

**Note**: For issues wherein the device is not connecting to IoT Hub, you will have to go thru OOBE first and then go thru the above steps to upgrade the azureyeemodule which will ensure the sample model deployment works.

**Comment by v-iskha** [comment]
@Neurotaur - Any update?

**Comment by v-iskha** [comment]
@Neurotaur - Since there is no response, we assume the issue to be resolved. Please email "aedppsup@microsoft.com" if you still need support on this issue.
