### ISSUE TITLE
DevKit SoftAP wifi access point shows up and disappears

### ISSUE THREAD

**Issue by coolsharepoint** [microsoft/Project-Santa-Cruz-Preview#162]
Steps:
- Set up all connections.
- Powered on the device. The SoftAP wifi access point shows up. When i enter the wifi password, it connected to the network and then the Wifi SSID disappears. I rebooted the devkit, same issue happens. Have tried multiple times, same issue.
- Weird Part, i see the device registered in IotHub with the DeviceId that was used before.

Note : Last week, i had registered the device and was able to work. I deleted the registered device from IoTHub and tried to register the device, this issue started happening.

I am stuck here ad not able to proceed any further.

![azure-device-error](https://user-images.githubusercontent.com/13283430/111414537-29e16180-86ae-11eb-8b57-a791691aba64.PNG)

**Comment by v-prsasa** [comment]
@coolsharepoint This is known issue- https://github.com/microsoft/Project-Santa-Cruz-Preview/blob/main/release-notes/known-issues.md. Please go through the link for reference.

**Comment by v-prsasa** [comment]
Closing as it's known issue.

**Comment by coolsharepoint** [comment]
Hi,
I have seen the issues page and i am not even seeing the devkit wifi hotspot to proceed. So technically blocked. Can you please help to resolve this issue?
