### ISSUE TITLE
DevKit SoftAP wifi access point didnt show up

### ISSUE THREAD

**Issue by coolsharepoint** [microsoft/Project-Santa-Cruz-Preview#164]
When the devkit is powered on, i am not seeing the softAP wifi access point to proceed. Tried rebotting the device multiple times, no luck.

**Comment by v-iskha** [comment]
@coolsharepoint - We have observed that this is a [known issue](https://github.com/microsoft/Project-Santa-Cruz-Preview/blob/main/release-notes/known-issues.md). Also if the host computer you will be using has an active WWAN/Cellular connection, disconnect from it before proceeding. This can sometimes cause interference to the SoftAP.

**Comment by coolsharepoint** [comment]
Followed the issue page. Disconnected the host wifi before connecting to the devkit softAP. When connected to the devkit wifi now, the devkit wifi disappears after the getting the code to copy and paste in the Microsoft device login page. At this point, Microsoft device login page is not accessible.

**Comment by v-iskha** [comment]
@coolsharepoint - Have you tried to click the button close to the LED to try turn ON/OFF the SoftAP? Let us know if that make any changes.

**Comment by v-iskha** [comment]
@coolsharepoint - Could you please provide below information as well

1. What OS you are using on the Host computer
2. Does the SoftAP name still show up in Windows as an available Access point which you could connect to?
3. Can you try this: When connecting to the Percept Wifi AP, check the "Connect Automatically" box.  Does this allow the connection state to be preserved when getting to the Device Code screens and beyond?
a.	Windows will eventually DISCONNECT AUTOMATICALLY from networks that do not show "internet access" and will try and revert to previous wifi connections.
4. If you setup/configured the device to connect to your local WIFI, that "connected" screen shows the device's IP address.  Running OOBE with that IP while the host PC is connected to their local Wifi AP should allow you to proceed.

Awaiting your feedback.

**Comment by coolsharepoint** [comment]
I am able to register the device. Thanks for the help. 
This ticket can be closed.
