### ISSUE TITLE
Not getting data from deployed custom vision model to the devkit

### ISSUE THREAD

**Issue by coolsharepoint** [microsoft/Project-Santa-Cruz-Preview#165]
Created a new vision project, trained the model and deployed the model to a devkit. 
The devkit is predicting objects instead of the deployed model. No trace of the custom vision model data is coming through.

**Comment by v-iskha** [comment]
@coolsharepoint - There is already an open [issue](https://github.com/microsoft/Project-Santa-Cruz-Preview/issues/157) reported earlier. The issue will be fixed in next OS software update for the devkit.

**Comment by v-iskha** [comment]
@coolsharepoint - We are pleased to announce the release of public software update today. Please [visit this](https://github.com/microsoft/Azure-Percept-Private-Preview#welcome-to-the-azure-percept-private-preview-github-page) page to update your dev kit's software and firmware today. It includes instructions as well.

You can also attend a drop-in call to get direct support. [Click here](https://github.com/microsoft/Azure-Percept-Private-Preview/blob/main/update-your-devkit-today/support-sessions.md) to see the schedule of calls or contact our team at aedppsup@microsoft.com
