### ISSUE TITLE
Unable to connect to Hidden SSID. Is this supported?

### ISSUE THREAD

**Issue by mikelor** [microsoft/Project-Santa-Cruz-Preview#166]
I've been working with our enterprise folks to setup an alternate SSID/Access Point that supports Pre-Shared Keys.

There is a requirement that they make the SSID a hidden network. I don't see away to "+ Add a Network Connection", similar to Windows 10. I don't see this under advanced network settings either.

If not, I'd like to submit a Feature Request for this.

**Comment by v-iskha** [comment]
@tsampige - Does Azure private preview DK supports "Pre-Shared Keys" Also the SSID is hidden. So can the device connect to hidden n/w. If not then customer is requesting this as a feature request on the same.

**Comment by tsampige** [comment]
+ Keith

**Comment by SillyKeith** [comment]
This feature is already implemented in the latest image.  The wifi page has an "Add hidden network" option at the bottom of the network scan results.
![hiddenssid](https://user-images.githubusercontent.com/28606059/111557166-644c0c80-8749-11eb-934e-b3e251e4970a.PNG)
