### ISSUE TITLE
Azure Percept Studio opens wrong video stream url after setting static IP address

### ISSUE THREAD

**Issue by jdiekhoff** [microsoft/Project-Santa-Cruz-Preview#167]
I initially setup my device to use a dynamic IP address. I have now set a static ip going through the oobe tool. However, when clicking "View stream" in Azure Percept Studio, the old ip address is launched. I can view the stream by manually going to the ip address that I set and it works, but would prefer that Azure Percept Studio launch with the correct ip.

**Comment by v-iskha** [comment]
@jdiekhoff - Hi Joseph, after setting the static IP using OOBE tool, could you please reboot the device and restart Azure Percept Studio and try if that helps.

**Comment by jdiekhoff** [comment]
@v-iskha thank you for the recommendation. I have rebooted the device and restarted Azure Percept Studio, but the old dynamic IP is still being used when opening a stream in Azure Percept Studio. I can still view the stream when manually opening a browser tab and typing in the static ip.

**Comment by v-iskha** [comment]
@EthanChangAED - Device is not getting static IP which has been assigned via OOBE, it is picking up old dynamic IP. Joseph was able to access the video stream by manually typing the static IP in browser.

**Comment by v-iskha** [comment]
@WendyAnn0079 - Azure Percept Studio is not getting static IP which has been assigned via OOBE, it is picking up old dynamic IP. Joseph was able to access the video stream by manually typing the static IP in browser.

**Comment by jdiekhoff** [comment]
I tested with another device, switching to a static IP and restarting does work. The correct IP is picked up on restart. The previous device is probably faulty, it is currently unresponsive. Closing.
