### ISSUE TITLE
Error: Unauthorized - When Trying to Add New DevKit to Existing IotHub

### ISSUE THREAD

**Issue by mikelor** [microsoft/Project-Santa-Cruz-Preview#170]
When trying to add a new DevKit to an existing IoTHub, I am getting an Error: Unauthorized
According to a cat /etc/adu-version the current version on the device is **2020.110.114.105**

I have successfully added other DevKits to this IoTHub in the past, but am unable to do this with a new set of hubs. I have tried to update the DevKit to the lastest version but ran into Issue #169 

Here is a screenshot of the error
![image](https://user-images.githubusercontent.com/341942/111713344-abe79c80-880c-11eb-97a7-95cab6c4aad8.png)

**Comment by v-prsasa** [comment]
@mikelor I hope you are following this link https://github.com/microsoft/Project-Santa-Cruz-Preview/blob/main/user-guides/getting_started/oobe.md .

**Comment by mikelor** [comment]
@v-prsasa, Yes. I am. (Although with the version I am on (see first post) the experience is different. Here is the screen prior to the Error - Unauthorized. I am able to see all of my IoT Hubs and all are enabled with DPS.

![image](https://user-images.githubusercontent.com/341942/111849565-20811080-88cb-11eb-946e-e279ea5e429a.png)

**Comment by mikelor** [comment]
@v-prsasa I also attempted to "Create a IoT Hub" as part of the OOBE flow, and register my devkit with that one. It failed with same error as well. See screenshots below.

![image](https://user-images.githubusercontent.com/341942/111851453-6c828400-88d0-11eb-8499-f122413372a1.png)

**Comment by v-iskha** [comment]
@mikelor - For IoT Hub please use [this](https://docs.microsoft.com/en-us/azure/iot-hub-device-update/create-device-update-account) document and let us know if that helps.

**Comment by mikelor** [comment]
It looks like the link referenced above is for updating a DevKit OTA with Azure Device Update. In order for that to occur, a DevKit has to be attached to an IoTHub, which is what this issue is.

An update on this, I was able to unpack a 3rd DevKit same version/batch as this (2020.110.114.105), and I was able to get it to attach to my existing IoTHub.  The only difference between the two, is the network I use for connectivity. 

Successful: Home/Consumer Network 
Unsuccessful: Enterprisey Type Cisco WAP with additional filtering and security.

I won't be able to troubleshoot the Enterprisey network until 2nd week of April. I'll take a look at the logs on the devkit once I'm back in the office.

Any other ideas?

**Comment by v-iskha** [comment]
@mikelor - Hi Mike, this is inform you that "EAP[PEAP/MSCHAP]", "captive portals", and "Enterprise EAP-TLS" connectivity is currently not supported.

**Comment by mikelor** [comment]
Thanks @v-iskha, this network is using WPA-2 with a Pre-Shared Key (Password), meaning it's supported and I am successfully able to connect to it. 

One of the "enterprisey" features on this network may be "[SSL Inspection](https://dzone.com/articles/what-is-ssl-inspection-why-use-ssl-inspection#)" which requires that the client (DevKit in this case) needs a known enterprise certificate installed. I'm not sure if this is the case with the network I'm connecting to, it's just a theory. I'm going to follow up with the Network Team

**Comment by v-iskha** [comment]
@mikelor - Thanks for your feedback Mike. WPA2 pre-shared keys (PSK) is designed for personal home use hence it is supported.

**Comment by v-iskha** [comment]
@mikelor - I am closing this issue, since you are now able to connect the device to existing IoT Hub.

**Comment by mikelor** [comment]
@v-iskha the only reason I am able to get it connected is because I am using my home network. I still have this issue on my office network setup specifically for this device. Please reopen it.

**Comment by v-iskha** [comment]
@mikelor - Any update from your office network team about the encryption/security they are using due to which device is not getting connecting to office network but works with your home network.

**Comment by mikelor** [comment]
@v-iskha I'll be back in the office next week and will update this issue then. I will have to update the devkit via the uuu method and then attempt the connection. Will most likely do this onTuesday

**Comment by mikelor** [comment]
Hey @v-iskha, I updated the DevKit to the latest version using the USB Method #2 (UUU) and was able to successfully attach devices. Closing this issue.
