### ISSUE TITLE
Update OOBE Documentation To Reflect Latest Image Experience

### ISSUE THREAD

**Issue by mikelor** [microsoft/Project-Santa-Cruz-Preview#171]
The [OOBE](https://github.com/microsoft/Project-Santa-Cruz-Preview/blob/main/user-guides/getting_started/oobe.md) documentation does not seem to reflect the latest image experience. 

According to to the [resolution](https://github.com/microsoft/Project-Santa-Cruz-Preview/issues/166#issuecomment-801535703) of #166 I should have the ability to "Add Hidden Network".   

In Step 3 of the OOBE it makes no mention, nor does the image show the capability to "Add Hidden Network".

Please add a note indicating what image version enables the "Add Hidden Network" feature. 

My version **2020.110.114.105** does not show the "Add Hidden Network" at the bottom like in the comment left by @SillyKeith .

![image](https://user-images.githubusercontent.com/341942/111851090-414b6500-88cf-11eb-8233-91a4c38d3164.png)

**Comment by mikelor** [comment]
Also, because of issue #169, I'm unable to add to a hidden network. :(

**Comment by v-iskha** [comment]
@mikelor - Apologies for the misunderstanding. On GitHub # 169, Keith wants to say that the enhancement has been implemented in the new upcoming software update. Hence he shared the new software screenshot that the Hidden WIFI feature is available in the new software update. Once the new software is available, you can update the same to get the new feature.

**Comment by mikelor** [comment]
@v-iskha Thanks, I will wait for the new image. 

But the main point of this issue is to update the OOBE docs to show that the Hidden Network experience is there or perhaps add a note about hidden networks. Perhaps getting @elqu20 to update the page. :)
