### ISSUE TITLE
Can't deploy a Custom Vision Model or a Sample Model on the Dev Kit

### ISSUE THREAD

**Issue by othmane-alaoui** [microsoft/Project-Santa-Cruz-Preview#172]
I am running on a 20210106.1146 version, and I can't deploy a Custom Vision Model or a Sample Model on the Dev Kit. 
I am getting this generic error: "Deployment was unsuccessful. Please try again".
<img width="369" alt="error" src="https://user-images.githubusercontent.com/59685366/112458590-3d9b6080-8d5d-11eb-8012-1160f5582629.PNG">

**Comment by v-prsasa** [comment]
@othmane-alaoui 
Can you update Azure Module using below steps

1.	Goto Azure Portal
2.	Select Iot Edge and click on your device under the Device ID tab.
3.	Goto Modules tab
4.	Click on “Azureeyemodule”
5.	On top, click on “Module Identity Twin”
6.	On Line # 21, you will find “ModelZipUrl”:””,
7.	In the double quotes enter https://aedsamples.blob.core.windows.net/vision/aeddevkitnew/product-detection.zip
8.	It will now look as “ModelZipUrl” : “https://aedsamples.blob.core.windows.net/vision/aeddevkitnew/product-detection.zip”
9.	Save it
10.	If the runtime status of azureeyemodule is not listed as running, click Set modules -> azureeyemodule. On the Module Settings page, set Desired Status to running and click Update.

Once above steps are completed, check if vision module shows as deployed. Try to deploy a sample model. 

Note: Sometimes you need to restart Azure portal and devkit after updating the Azure module

For screenshot/guide refer this [link](https://github.com/microsoft/Project-Santa-Cruz-Preview/blob/main/user-guides/prototyping/containers/eye_module_overview.md#how-to-locate-and-edit-your-module-identity-twin-settings).

**Comment by othmane-alaoui** [comment]
I tried this method, I am still getting the same error. 
The modules seems to be running with no errors: 
![image](https://user-images.githubusercontent.com/59685366/112461850-a7693980-8d60-11eb-9497-2c2127636369.png)
I also noticed a message saying: "Vision module not installed"; 
![image](https://user-images.githubusercontent.com/59685366/112462019-e26b6d00-8d60-11eb-85ef-651162bd1cb1.png)
I think it's a related problem. Am I missing another module?
Also, FYI I updated the firmware manually from version 2020.110.114.105 to 20210106.1146 using [USB update method #2: NXP UUU tool](https://github.com/microsoft/Project-Santa-Cruz-Preview/blob/main/user-guides/updating/usb_updating.md#usb-update-method-2-nxp-uuu-tool) .

**Comment by v-iskha** [comment]
@othmane-alaoui - Could you please share the device logs for investigation.
You can share the logs generated from the following commands?
sudo docker logs azureeyemodule > azureeyemodule.log
sudo docker logs edgeAgent >edgeAgent.log

**Comment by othmane-alaoui** [comment]
@v-iskha Thank you for your answer.
Here is my two logs file: 

- azureeyemodule logs: [azureeyemodule-2021-03-26--09-07-01.log](https://github.com/microsoft/Project-Santa-Cruz-Preview/files/6210608/azureeyemodule-2021-03-26--09-07-01.log)

- edgeAgent logs: [edgeAgent-2021-03-26--09-09-03.log](https://github.com/microsoft/Project-Santa-Cruz-Preview/files/6210612/edgeAgent-2021-03-26--09-09-03.log)

I tried redeploying the models many times, but there is nothing appearing on the log files.

**Comment by v-iskha** [comment]
@othmane-alaoui - “According to the logs, it seems that the Eye SoM wasn't recognized correctly. Please ensure the USB connection between the carrier board and the Eye SoM is connected properly? Also make sure you are using a usb-c to usb-c cable"

**Comment by v-iskha** [comment]
@othmane-alaoui - Any updates on the device.

**Comment by v-iskha** [comment]
@othmane-alaoui - There is an update in azuremodule which you can upgrade by performing below steps

Go to IoT Hub -> IoT Edge -> Select Device -> click on Set Modules -> select azureyemodule, 
then change image uri to **mcr.microsoft.com/azureedgedevices/azureeyemodule:2103-2** 
and click update -> click on Review + create -> click on create. 

The module download will get initiated. To verify if the download is completed, click on Azureeyemodule and check if the reported value is same as desired value.

**Note**: For issues wherein the device is not connecting to IoT Hub, you will have to go thru OOBE first and then go thru the above steps to upgrade the azureyeemodule which will ensure the sample model deployment works.

**Comment by v-iskha** [comment]
@othmane-alaoui - Any progress?

**Comment by othmane-alaoui** [comment]
@v-iskha Thank you for your answers. 
I just had a hardware problem. With a little accident the connector between the Eye SoM and the carrier board got broken. So right now, I can't test anything unfortunately.

**Comment by v-iskha** [comment]
@othmane-alaoui - Very sorry to hear that. Since we cannot do any further troubleshooting here, I am closing this issue from our end.
