### ISSUE TITLE
Unable to start OOBE after OTA Update to 2021.101.106.118 - Argh!

### ISSUE THREAD

**Issue by mikelor** [microsoft/Project-Santa-Cruz-Preview#173]
Okay, after failing to update a DevKit via USB (#169), I was able to successfully connect to an IoTHub and get the DevKit updated via an OTA Update to 2021.101.106.118

However it
  1. Lost it's Internet WiFi Configuration
  2. No longer starts the OOBE at either 10.1.1.1 or 10.1.1.1:4242

I have powered down, disconnected from power multiple times
It does not work.

This is extremely frustrating. I have yet to get a consistent update experience from 2021.101.106.118 yet.

**Comment by mikelor** [comment]
I should also add. I attempted to troubleshoot using the method below (defined on [this page](https://github.com/microsoft/Project-Santa-Cruz-Preview/blob/main/release-notes/known-issues.md)
![image](https://user-images.githubusercontent.com/341942/112554583-d2b15000-8d83-11eb-8225-e68a968131f8.png)

But what IP address should I be looking for?

**Comment by v-iskha** [comment]
@mikelor - Apologies for inconvenience. Since you have done an OTA update, please use this [link](https://github.com/microsoft/Project-Santa-Cruz-Preview/blob/main/user-guides/updating/ota_update.md) for guidance. It also has its separate known issues at the bottom of the page.

**Comment by mikelor** [comment]
Thanks @v-iskha I did review those, but none of them match the issue that I am experiencing. I am unable to get the OOBE to run.

**Comment by v-iskha** [comment]
@WendyAnn0079 - Mike is unable to run the OOBE after updating the software to 2021.101.106.118.

**Comment by mikelor** [comment]
I'm going to close this. OTA is Broken, Broken, Broken.
After setting up 4 DevKits and updating them with various methods, I've found the only reliable way to update DevKits is via USB Method 2 (Using the UUU tool).

Even though the OTA updated the version, I still had inconsistencies. Closing this Issue since there is a workaround.
