### ISSUE TITLE
Examples of working with both Eye SoM and Ear SoM

### ISSUE THREAD

**Issue by lxyea** [microsoft/Project-Santa-Cruz-Preview#174]
Hi, project Santa-cruz team (Azure Percept team),
I can only see AI Edge examples that work with Eye Module or Ear Module separately. Do you have an example of using both modules, i.e. some use cases that will take voice as well as vision input and then get some joint insight?
Further to this, is there any Actuator SoM in the roadmap?

**Comment by v-iskha** [comment]
@tsampige - Question from customer, _"Do you have an example of using both (Eye & Ear) modules, i.e. some use cases that will take voice as well as vision input and then get some joint insight? Further to this, is there any Actuator SoM in the roadmap?"_

**Comment by v-iskha** [comment]
@lxyea - Hi Larry, we do not have any examples at the moment, hence noted & closing this as a new feature enhancement request.
