### ISSUE TITLE
access to Getting Started Videos

### ISSUE THREAD

**Issue by jacksongitpro** [microsoft/Project-Santa-Cruz-Preview#175]
hello how can I view the Getting Started Videos! I need view them for complete the Project-Santa-Cruz preview! can you help me please ?

**Comment by v-iskha** [comment]
@jacksongitpro - Please share your email ID we will do the needful.

**Comment by jacksongitpro** [comment]
> @jacksongitpro - Please share your email ID we will do the needful.

jacksong@exo.com.ar thanks

**Comment by v-iskha** [comment]
@jacksongitpro - Access has been granted.
