### ISSUE TITLE
I cannot access to getting_started videos

### ISSUE THREAD

**Issue by jacksongitpro** [microsoft/Project-Santa-Cruz-Preview#177]
![image](https://user-images.githubusercontent.com/77233912/112705595-60716600-8e7e-11eb-9168-ecc4ae2305a3.png)

thanks for the access. but, now when I try to enter, it asks me to change the password which is impossible since our domain is on-premises and it is not from azure ad

![image](https://user-images.githubusercontent.com/77233912/112705765-f6a58c00-8e7e-11eb-8eaa-197219968790.png)

How could I solve this problem?
Thank you very much for the help

**Comment by v-prsasa** [comment]
@jacksongitpro  Santa Cruz [portal](https://projectsantacruz.microsoft.com/) and onboarding is no longer needed. So you might face some issues with the portal as well. For any guidance or support you can refer official Santa Cruz [GitHub](https://github.com/microsoft/Project-Santa-Cruz-Preview#welcome-to-the-project-santa-cruz-private-preview) channel.

**Comment by jacksongitpro** [comment]
I regard to the access to getting_started. when I try to acces it ask me to **update my password**

which is impossible since our domain is on-premises and it is not from azure ad

**Comment by v-iskha** [comment]
@jacksongitpro - "Update your password" is the message from your account ID, nothing to do with giving access. We simply add the email ID to provide access.

**Comment by v-iskha** [comment]
@jacksongitpro - Just looking for update on this. If you are having issues with your existing email account, please share alternate email address and we will add it for you.
