### ISSUE TITLE
loss password root

### ISSUE THREAD

**Issue by jacksongitpro** [microsoft/Project-Santa-Cruz-Preview#180]
how  can I restore the system properly?  I have loss the root password

**Comment by mikelor** [comment]
@jacksongitpro you could try using Method #2 of Updating the Image with the USB UUU Tool, then try and sign in using the default root password.

**Comment by jacksongitpro** [comment]
> @jacksongitpro you could try using Method #2 of Updating the Image with the USB UUU Tool, then try and sign in using the default root password.

hello!! thanks for try help me, I've used the method #3 https://github.com/microsoft/Project-Santa-Cruz-Preview/blob/main/user-guides/updating/usb_updating.md
