### ISSUE TITLE
Unable to recover azureeyemodule after disabling and re-enabling connection to iot hub

### ISSUE THREAD

**Issue by mklasby** [microsoft/Project-Santa-Cruz-Preview#183]
We are working with 4 azure percept devices and each  device's `azureeyemodule` has entered a failed state with exit code 135 after disabling / enabling the devices on iot hub. We have tried restarting the container, power cycling the devices, and setting the modules from desired status running to stopped and back to running without any luck.  

See docker container logs attached (warning, large file). It appears that the `inferenceStream4` stream is full and causes a blocked event. I can see data read failures linked to a failed condition `event->header.flags.bitField.ack != 1`. 

When we tried to restart the container manually, docker threw the following error: 
`root@scz-3623bb810842 [ / ]# sudo docker container run cdd6840c0b55`

`docker: Error: error contacting notary server: dial tcp: lookup notary.docker.io on 127.0.0.53:53: read udp 127.0.0.1:58708->127.0.0.53:53: i/o timeout.`

`See 'docker run --help'.`

Any suggested procedures to recover the devices is welcomed. Ideally, we would like to be able to reenable to module remotely, without direct access to the devices on the local network. 

[eyeLogs.zip](https://github.com/microsoft/Project-Santa-Cruz-Preview/files/6253447/eyeLogs.zip)

**Comment by MS-Nikunja** [comment]
@tsampige -  User is having issues with azureeyemodule. Please advise.

**Comment by mklasby** [comment]
Update: We have been able to recover the devices, but only by deleting them from the iot hub and re-registering through the OOBE process. I believe this issue should remain open as this seems to be unintended behaviour

**Comment by v-iskha** [comment]
@mklasby - Thanks for the feedback. The fix is expected in next software update hence closing this issue.

**Comment by mklasby** [comment]
Thank you @v-iskha, we will try the update and report back if we have any further issues.

**Comment by v-iskha** [comment]
@mklasby - We are pleased to announce the release of public software update today. Please [visit](https://github.com/microsoft/Azure-Percept-Private-Preview#welcome-to-the-azure-percept-private-preview-github-page) this page to update your dev kit's software and firmware today. It includes instructions as well.
You can also attend a drop-in call to get direct support. [Click here](https://github.com/microsoft/Azure-Percept-Private-Preview/blob/main/update-your-devkit-today/support-sessions.md) to see the schedule of calls or contact our team at aedppsup@microsoft.com

**Comment by mklasby** [comment]
Thank you @v-iskha, I'll update and confirm the fix on our end
