### ISSUE TITLE
OTA Deployment fails with incompatible device

### ISSUE THREAD

**Issue by kaareseras** [microsoft/Project-Santa-Cruz-Preview#185]
Updating device from 2020.110.114.105 --> 2021.101.106.118

Updating using ADU gives just says that device is incompatible in the portal

![image](https://user-images.githubusercontent.com/15147387/113847188-7e509c00-9797-11eb-9396-2c982c6b0f99.png)

**Comment by MS-Nikunja** [comment]
@kaareseras - Have you tried to update the device via USB? Currently it is recommended to perform USB update method instead of OTA.

**Comment by kaareseras** [comment]
Hi, I have tried the USB also now, however, it does not update the FW

I Copied the Microsoft-PE-101-2021.101.106.118.swu to the root of a Fat32 formated USB stik pluegd in in, and rebooted both using the reboot command and the button long press.

Still I'm running 2020.110.114.105 on the device

**Comment by v-iskha** [comment]
@kaareseras - Question for you, 1. Do you have a private preview device or you have purchased public preview via Microsoft Store? 
2. From where have you downloaded the firmware (because Private preview and Public preview are having different FW). You will not be able to update public preview FW on private preview device and vice-versa.

**Comment by kaareseras** [comment]
I managed to update the device using the UUU tool, thank you

**Comment by v-iskha** [comment]
@kaareseras @mikelor - We are pleased to announce the release of public software update today. Please [visit this](https://github.com/microsoft/Azure-Percept-Private-Preview#welcome-to-the-azure-percept-private-preview-github-page) page to update your dev kit's software and firmware today. It includes instructions as well.
You can also attend a [drop-in call](https://github.com/microsoft/Azure-Percept-Private-Preview/blob/main/update-your-devkit-today/support-sessions.md) to get direct support. Click here to see the schedule of calls or contact our team at aedppsup@microsoft.com
