### ISSUE TITLE
ADU Account creation failed during OOBE experience

### ISSUE THREAD

**Issue by jseokkim** [microsoft/Project-Santa-Cruz-Preview#186]
I have tried to complete OOBE through https://projectsantacruz.microsoft.com/

Set ADU Service (Azure Device Update) failed due to the the following error message.
The message doesn't provide any actionable log or tips to resolve the error.
Two error messages popped up with "ADU account creation error" and "ADU instance creation error"

How can we collect the proper log for the issue resolution?

![ADU_Account_Creation_Error](https://user-images.githubusercontent.com/43247951/114435124-a9146900-9b78-11eb-879b-d3dccc48b9b7.png)

![ADU_Instance_Creation_Error](https://user-images.githubusercontent.com/43247951/114434741-31463e80-9b78-11eb-8ee0-fe5bdc465265.png)

**Comment by v-iskha** [comment]
@jseokkim - Please refer [this](https://github.com/microsoft/Project-Santa-Cruz-Preview#getting-started) page for step by step guide to configure and use the devkit. 
Regarding ADU, it is recommended to updated the DevKit using the USB Method #[2](https://github.com/microsoft/Project-Santa-Cruz-Preview/blob/main/user-guides/updating/usb_updating.md#usb-update-method-2-nxp-uuu-tool) NXP UUU tool

**Comment by v-iskha** [comment]
@jseokkim - Any updates?

**Comment by v-iskha** [comment]
@jseokkim - Any update on the issue, did it got fixed.

**Comment by jseokkim** [comment]
Thanks for helping out.

After rebooting, OOBE is working and I could complete setup via OOBE.

Thanks,
Jaeseok
________________________________
