### ISSUE TITLE
Factory reset - where are the files?

### ISSUE THREAD

**Issue by dankronstal** [microsoft/Project-Santa-Cruz-Preview#188]
I'd like to factory reset my Percept, which sounds like will be "Method 2" here: 

https://github.com/microsoft/Project-Santa-Cruz-Preview/blob/main/user-guides/updating/usb_updating.md#usb-update-method-2-nxp-uuu-tool 

however I do not see any update files listed. Is there another place I can find them?
<img width="1111" alt="Screenshot 2021-04-15 141857" src="https://user-images.githubusercontent.com/1483454/114934578-4a105780-9df7-11eb-9600-be60c5cddb63.png">

**Comment by v-iskha** [comment]
@dankronstal - Since we are near in releasing the software update to public, all the old files are removed from project santacruz portal. There are different instructions overall to update the public released software update which will be shared very soon. Apologies for any inconvenience.

**Comment by v-iskha** [comment]
@dankronstal - I am closing this case as per my earlier comment. We will advise once the new software update is available for public with instructions.

**Comment by v-iskha** [comment]
@dankronstal - We are pleased to announce the release of public software update today. Please visit [this](https://github.com/microsoft/Azure-Percept-Private-Preview#welcome-to-the-azure-percept-private-preview-github-page) page to update your dev kit's software and firmware today. It includes instructions as well.
You can also attend a drop-in call to get direct support. [Click here](https://github.com/microsoft/Azure-Percept-Private-Preview/blob/main/update-your-devkit-today/support-sessions.md) to see the schedule of calls or contact our team at aedppsup@microsoft.com
