### ISSUE TITLE
[BUG] Unable to complete the OTA update

### ISSUE THREAD

**Issue by uriel-kluk** [microsoft/Project-Santa-Cruz-Preview#35]
Loving the SCZ kit and pipeline, awesome work.

Steps:
1. Went through the onboarding portal, everything completed on time, although I so the note about the 5 business days for ADU to complete.
1. Obviously I didn't wait for the 5 days to start working with my system and I found some issues that have been identified and fixed in the new module update. Mainly: After a reboot the edge can't connect. the workaround is to SSH and do a `systemctl restart iotedge`
1. Followed the instructions to upgrade the firmware and after 2 days I am now able to get the job running after importing the files. 
![image](https://user-images.githubusercontent.com/41210115/92125499-b8525d80-edc4-11ea-8959-bc88ee9aeea3.png)
1. But when I close the dialog and go back to the import pane, there are no entries
![image](https://user-images.githubusercontent.com/41210115/92125669-e46dde80-edc4-11ea-9742-d0a3548e70cb.png)
1. I tried to go back to the onboarding steps and restart from the beginning, but now the page starts on the summary portion and I don't have a chance to repeat the steps:
![image](https://user-images.githubusercontent.com/41210115/92125886-272fb680-edc5-11ea-9635-0fb29efa04ed.png)

**Comment by v-iskha** [comment]
Alex Akesson's Comment on 24-Sep-2020 - Fixed and guidance emailed to Mesh. Awaiting feedback prior to closing.

**Comment by v-iskha** [comment]
Closing this ticket as Bug # 29024600 has been resolved for this issue.
