### ISSUE TITLE
Enabling ADU results in an error during onboarding

### ISSUE THREAD

**Issue by MatthijsvdVeer** [microsoft/Project-Santa-Cruz-Preview#78]
During the onboarding steps, when I try to enable ADU and hit the Next button, I see an error.

![image](https://user-images.githubusercontent.com/736727/101336073-4d5c6b00-387a-11eb-91d5-a7bea26c2d2d.png)

This might be related to the fact that while I can see the *Device Update for IoT Hubs* feature, I can't seem to create a new one in the portal:
![image](https://user-images.githubusercontent.com/736727/101336212-7b41af80-387a-11eb-923a-88c9e9255793.png)

**Comment by v-prsasa** [comment]
@mimcco Can you look into this issue ?

**Comment by mimcco** [comment]
@MatthijsvdVeer - I just hit this same issue yesterday. I'm still working through it with our engineering team but hopefully we can get both of our issues resolved. First, can you try again in a private browser window and see if that does the trick? It didn't work for me, but it's always a good step to get the cookies/cache out of the way. If that doesn't work, can you send mail to aedppsup@microsoft.com? We're going to want to collect some details about your Azure subscription so we can look at some logs. Thanks!

**Comment by MatthijsvdVeer** [comment]
Tried in a private browser window, and still getting the same error. I'll send an email right away! Thanks @mimcco

**Comment by jamhamlee** [comment]
Same problem here. Private Window won't work.

**Comment by mustafakasap** [comment]
Same here. 

Looking into this issue by manually enabling ADU...

**Comment by CortalUX** [comment]
I'm still getting this issue with onboarding a new device.
I have the same issue as @MatthijsvdVeer, and can't access this from the portal
![image](https://user-images.githubusercontent.com/19361656/102513952-ca11f500-4083-11eb-85c3-d6e6ab484f14.png)
If I disable the ADU, then the page re-opens with ADU pre-selected, and asks for an AAD app - and the Blazor app crashes
![image](https://user-images.githubusercontent.com/19361656/102514002-dac26b00-4083-11eb-8fa4-b23367d5c1cb.png)

**Comment by v-prsasa** [comment]
@MatthijsvdVeer This is any expected error. It is outside of our control as it is handled by Azure AFEC team (unfortunately)
Could you try re-registering the the Microsoft.DeviceUpdate RP and then returning to the SCZ website?

**Comment by jamhamlee** [comment]
I changed my user type to OWNER, then I finished the onboarding. Hope this help.

**Comment by elqu20** [comment]
This is now documented in the Known Issues article (https://github.com/microsoft/Project-Santa-Cruz-Preview/blob/main/release-notes/known-issues.md). Please try the workaround listed.

**Comment by MatthijsvdVeer** [comment]
@v-prsasa that did the trick. Unregistering and re-registering resolved the issue.
