### ISSUE TITLE
screenshots need to be updated

### ISSUE THREAD

**Issue by ozhernan** [microsoft/Project-Santa-Cruz-Preview#82]
In https://github.com/microsoft/Project-Santa-Cruz-Preview/blob/main/user-guides/prototyping/create-nocode-vision.md , the portal portal UI has changed so the screenshots need to be updated

**Comment by MS-Nikunja** [comment]
Hi @elqu20, can you please look into this. Thanks.

**Comment by elqu20** [comment]
Updated. Thanks for the heads-up!
