### ISSUE TITLE
documentation not clear

### ISSUE THREAD

**Issue by ozhernan** [microsoft/Project-Santa-Cruz-Preview#85]
https://github.com/microsoft/Project-Santa-Cruz-Preview/blob/main/user-guides/general/troubleshooting/ssh_and_serial_connection_setup.md

In the doc above, the serial connections steps are not clear, it doesn't specify the port on the dev kit we have to use for the serial connection. 

Also, to enable SSH you have to complete OOBE so it's safe to assume the dev kit is connected to the network and we should use the dev kit IP address instead of the softAP as the first option.

**Comment by MS-Nikunja** [comment]
Hi @elqu20, can you look into this.

**Comment by mimcco** [comment]
assigning to @elqu20

**Comment by elqu20** [comment]
Documentation has been updated with additional serial connection guidance.

In regards to SSH, you do not need to complete OOBE to SSH into your device. OOBE allows you to create an SSH login (which is optional), but you may still log in to your device through SSH as root.
