### ISSUE TITLE
Remote trust data does not exist: AIVisionDevKitGetStartedModule will not run on dev-kit

### ISSUE THREAD

**Issue by ncgregpruett** [microsoft/Project-Santa-Cruz-Preview#87]
Installed using Set Modules -> Add -> Marketplace

via ssh -- docker images shows this version installed:

[ ~ ]$ sudo docker images
...
mcr.microsoft.com/aivision/visionsamplemodule                 1.1.3-arm32v7       f8a7667eb3ea        18 months ago       659MB

In Azure Portal, under Iot Hub -> Automatic Device Management -> IoT Edge -> Modules
shows: 
AIVisionDevKitGetStartedModule
IoT Edge Custom Module
Specified in Deployment:  Yes
Reported by DeviceL:  Yes
Runtime Status:  backoff
Error Code: 1

Trying to run the container manually via ssh:

[ ~ ]$ sudo docker run mcr.microsoft.com/aivision/visionsamplemodule
docker: Error: remote trust data does not exist for mcr.microsoft.com/aivision/visionsamplemodule: mcr.microsoft.com does not have trust data for mcr.microsoft.com/aivision/visionsamplemodule.

**Comment by MS-Nikunja** [comment]
Hi @ncgregpruett, we are looking into it.

**Comment by v-prsasa** [comment]
@v-robgi  Could you please look into this issue?

**Comment by KStClair72** [comment]
Hi @ncgregpruett, the AIVisionDevKitGetStartedModule is for ARM32 architecture and Santa Cruz devkit is ARM64. Even if it would run it wouldn't work, because it's meant for different HW.  Thank you.
