### ISSUE TITLE
Project Santa Cruz Onboarding - Incorrect Screen Grabs for Step 8

### ISSUE THREAD

**Issue by mikelor** [microsoft/Project-Santa-Cruz-Preview#89]
The screenshot shown in Step 8 of [Project Santa Cruz onboarding](https://github.com/microsoft/Project-Santa-Cruz-Preview/blob/main/user-guides/getting_started/azure-subscription-onboarding.md) shows a [screen shot](https://github.com/microsoft/Project-Santa-Cruz-Private-Preview/blob/main/user-guides/getting_started/getting_started_images/onboarding_dps_adu.png) that is different than the current experience.

Instead I see
![image](https://user-images.githubusercontent.com/341942/103044732-7cd7cc80-4536-11eb-91ce-85518995ff4b.png)

Screenshot for Step 8. Should be updated to reflect the current experience.

**Comment by mikelor** [comment]
After setting up the Device Provisioning Service by selecting [Next], I am presented with another step that does not correspond to Step 8.

Set ADU Service 
![image](https://user-images.githubusercontent.com/341942/103045053-d5f43000-4537-11eb-984a-339d3af5017d.png)

After selecting [Next] on the above screen, I am presented with the screen below

Set Automatic Import Update Service
![image](https://user-images.githubusercontent.com/341942/103045379-199b6980-4539-11eb-913e-ef22eaf36ce6.png)

This does not correspond with the screen shown in Step 9.

As I recall from an earlier setup and discussion with the product team, this is a "Feature Flag" that has been enabled, but not necessarily needed to continue.

New users to this experience will be confused because the docs do not match the experience.

**Comment by MS-Nikunja** [comment]
Hi @elqu20, can you look into this.

**Comment by elqu20** [comment]
Documentation has been updated. Thanks for the heads-up!
