### ISSUE TITLE
steps 4 - 8 images are very small

### ISSUE THREAD

**Issue by ozhernan** [microsoft/Project-Santa-Cruz-Preview#92]
in https://github.com/microsoft/Project-Santa-Cruz-Preview/blob/main/user-guides/updating/ota_update.md

in steps 4 to 8 images atre very small and is very hard to see them

**Comment by v-iskha** [comment]
@elqu20 - Hi Elena, there are few images which are very small and not clearly visible under ota_update page.

**Comment by elqu20** [comment]
fixed
