### ISSUE TITLE
Claim Device Fails with "Invalid Device Id" when entering exact GUID (including m:)

### ISSUE THREAD

**Issue by mikelor** [microsoft/Project-Santa-Cruz-Preview#93]
I'm attempting to register my Santa Cruz DevKit Device using the instructions found [here](https://github.com/microsoft/Project-Santa-Cruz-Preview/blob/main/user-guides/getting_started/register_your_device.md)

When I enter my Hardware ID on the [Project Santa Cruz page](https://projectsantacruz.microsoft.com/ClaimDevice), I get an "Invalid Device Id" error when entering the Device ID returned in my SSH session (m:XXXXXXX). See screenshot below

![image](https://user-images.githubusercontent.com/341942/103297673-addc5500-49ad-11eb-82f8-0613a8ff1647.png)

If I replace the (m:) with a (t:) it registers (see screenshot above showing the same GUID but with t: prefix in Claimed Devices). But in Step 4 (See screenshot below) it says I can use either m: or t: .  So should I be able to enter m:?  Also please note that the Hardware ID graphic in step 6 is 404 
![image](https://user-images.githubusercontent.com/341942/103298288-da44a100-49ae-11eb-9613-0b0dbd3d7e08.png)

**Comment by elqu20** [comment]
Fixed image url.

**Comment by elqu20** [comment]
I think this is a question for @ikhapova.

**Comment by mimcco** [comment]
Hi @mikelor - the fact your device ID begins with "m:" indicates there may be an issue with the TPM on the device. Do you consistently get a GUID that starts with "m:" when you run the "azure-device-health-id" command?

**Comment by elqu20** [comment]
The documentation has been updated to reflect that the  GUID must start with "t:".

**Comment by mikelor** [comment]
Weird, I now consistently get a t: and the GUID is different than what I was getting before.
I also see that the documentation has been updated to reflect that it must start with a t:

Let me know if you need more information, otherwise this issue can be closed.

**Comment by mimcco** [comment]
Thanks for checking again. The fact that it is a completely different GUID is expected. Please try using that GUID on the Claimed Devices page/process.

When we get a device ID that does not start with "t:", it indicates that the TPM is not detected on the device. So we're very interested in investigating whenever that happens. Thanks!

**Comment by mikelor** [comment]
Okay, it worked. I was able to use the t:GUID and get the device registered. If it occurs again, I'll follow the updated instructions per changes made by @elqu20 to this [page](https://github.com/microsoft/Project-Santa-Cruz-Preview/blob/main/user-guides/getting_started/register_your_device.md)

"If your GUID starts with "m:" or another character, please contact aedppsup@microsoft.com for support."
