### ISSUE TITLE
cable not supplied

### ISSUE THREAD

**Issue by ozhernan** [microsoft/Project-Santa-Cruz-Preview#94]
In https://github.com/microsoft/Project-Santa-Cruz-Preview/blob/main/user-guides/updating/usb_updating.md
in Method 2 Step 8 says that the usb-c to usb-A cable is supplied, that cable doesn't come with the dev kit (at least not with mine), also a picture showing the connection would be very useful.

**Comment by mimcco** [comment]
Following up with Oz offline. If anyone else did not receive a USB A to USB C cable with their dev kit, send email to aedppsup@microsoft.com.

**Comment by mimcco** [comment]
It is by design that dev kits do not include USB A to USB C cables. @elqu20, please update the documentation to make that more clear.

**Comment by elqu20** [comment]
Documentation has been updated.
