### ISSUE TITLE
HSM Failure on Device Registration

### ISSUE THREAD

**Issue by dillten** [microsoft/Project-Santa-Cruz-Preview#95]
Following the OOBE instructions to register the device with IoT Hub, once the Azure login is complete in the OOBE and the IoT Hub has been selected, the "Finalizing the Setup" page runs infinitely. 

Running the logs on edgeAgent shows the following error:

```
<6> 2021-01-04 23:32:19.194 +00:00 [INF] - Experimental features configuration: {"Enabled":false,"DisableCloudSubscriptions":false}
<6> 2021-01-04 23:32:20.038 +00:00 [INF] - Installing certificates [CN=Test Edge Owner CA:04/04/2021 16:25:59] to Root
<6> 2021-01-04 23:32:21.062 +00:00 [INF] - Starting metrics listener on Host: *, Port: 9600, Suffix: /metrics
<6> 2021-01-04 23:32:22.175 +00:00 [INF] - Updating performance metrics every 05m:00s
<6> 2021-01-04 23:32:22.210 +00:00 [INF] - Started operation Get system resources
<6> 2021-01-04 23:32:22.221 +00:00 [INF] - Collecting metadata metrics
<6> 2021-01-04 23:32:22.562 +00:00 [INF] - Set metadata metrics: 1.0.10.4.37804714 (57772714c81c8b823a5ef05bf11bf343b923fb6a), {"Enabled":false,"DisableCloudSubscriptions":false}, {"OperatingSystemType":"linux","Architecture":"aarch64","Version":"1.0.9.1","Provisioning":{"Type":"","DynamicReprovisioning":false},"ServerVersion":"","KernelVersion":"","OperatingSystem":"","NumCpus":0,"Virtualized":""}, True
<6> 2021-01-04 23:32:22.691 +00:00 [INF] - Started operation Checkpoint Availability
<6> 2021-01-04 23:32:22.716 +00:00 [INF] - Started operation refresh twin config
<6> 2021-01-04 23:32:22.839 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_Tcp_Only...
<6> 2021-01-04 23:32:25.535 +00:00 [INF] - Created persistent store at /tmp/edgeAgent
<6> 2021-01-04 23:32:26.014 +00:00 [INF] - Started operation Metrics Scrape
<6> 2021-01-04 23:32:26.015 +00:00 [INF] - Started operation Metrics Upload
Scraping frequency: 01:00:00
Upload Frequency: 1.00:00:00
<6> 2021-01-04 23:32:27.459 +00:00 [INF] - Registering request handler UploadModuleLogs
<6> 2021-01-04 23:32:27.460 +00:00 [INF] - Registering request handler GetModuleLogs
<6> 2021-01-04 23:32:27.461 +00:00 [INF] - Registering request handler UploadSupportBundle
<6> 2021-01-04 23:32:27.462 +00:00 [INF] - Registering request handler RestartModule
<6> 2021-01-04 23:32:28.120 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_WebSocket_Only...
<4> 2021-01-04 23:32:29.351 +00:00 [WRN] - Error creating a device-to-cloud connection
System.AggregateException: One or more errors occurred. (Error calling SignAsync: Module not found
        caused by: Signing error occurred.
        caused by: An error occurred in the key store.
        caused by: HSM failure
        caused by: HSM API failure occurred: 478, StatusCode: 404) (Error calling SignAsync: Module not found
        caused by: Signing error occurred.
        caused by: An error occurred in the key store.
        caused by: HSM failure
        caused by: HSM API failure occurred: 478, StatusCode: 404)
 ---> Microsoft.Azure.Devices.Client.HsmAuthentication.HttpHsmComunicationException: Error calling SignAsync: Module not found
        caused by: Signing error occurred.
        caused by: An error occurred in the key store.
        caused by: HSM failure
        caused by: HSM API failure occurred: 478, StatusCode: 404
```

The device is showing in the Azure portal but is not reporting status and will not receive updates.

**Comment by SillyKeith** [comment]
Can you see if restarting the iotedge service (possibly twice) resolves this for you?  

`systemctl restart iotedge`

Could you also tell us what build you are using by sending us the output of these two files?
```
cat /etc/os-subrelease
cat /etc/adu-version
```

**Comment by dillten** [comment]
Restart did not resolve.

```BUILDER_NAME=Microsoft.EdgeOS
BUILD_DATE="2020-10-14T05:20:16Z"
ID=santacruz
VERSION_ID=2008
NAME="Santa Cruz Mariner"
VERSION="Drop 2008"
BRANCH=""
COMMIT_ID=""```

```
$ cat /etc/adu-version
2020.110.114.105
```

Here's the iotedge service attempting to create the edgeagent module. 

```
Jan 06 16:39:50 scz-b27c545fe39e iotedged[28594]: 2021-01-06T16:39:50Z [INFO] - Pulling image mcr.microsoft.com/azureiotedge-agent:1.0.9.2...
Jan 06 16:39:50 scz-b27c545fe39e iotedged[28594]: 2021-01-06T16:39:50Z [INFO] - Successfully pulled image mcr.microsoft.com/azureiotedge-agent:1.0.9.2
Jan 06 16:39:50 scz-b27c545fe39e iotedged[28594]: 2021-01-06T16:39:50Z [INFO] - Creating module edgeAgent...
Jan 06 16:39:50 scz-b27c545fe39e iotedged[28594]: 2021-01-06T16:39:50Z [WARN] - Could not create module
 edgeAgent
Jan 06 16:39:50 scz-b27c545fe39e iotedged[28594]: 2021-01-06T16:39:50Z [WARN] -         caused by: erro
r creating overlay mount to /var/lib/docker/overlay2/079cc468b809fab381f05e9de43eaa86db357fce9c034770a766b04d2e10cc90-init/merged: too many levels of symbolic links
Jan 06 16:39:50 scz-b27c545fe39e iotedged[28594]: 2021-01-06T16:39:50Z [INFO] - [mgmt] - - - [2021-01-06 16:39:50.706946141 UTC] "PUT /modules/edgeAgent?api-version=2019-11-05&start=true HTTP/1.1" 500 Internal Server Error 282 "-" "-" auth_id(-)
Jan 06 16:39:50 scz-b27c545fe39e iotedged[28594]: 2021-01-06T16:39:50Z [ERR!] - server connection error
: (unknown)
Jan 06 16:39:50 scz-b27c545fe39e iotedged[28594]: 2021-01-06T16:39:50Z [ERR!] - error writing a body to
 connection: Broken pipe (os error 32)```

**Comment by dillten** [comment]
I was able to work around the issue by forcefully removing all of the preloaded docker images, thereby requiring new ones to be pulled at startup.
