### ISSUE TITLE
documentation not clear

### ISSUE THREAD

**Issue by ozhernan** [microsoft/Project-Santa-Cruz-Preview#96]
In https://github.com/microsoft/Project-Santa-Cruz-Preview/blob/main/user-guides/updating/usb_updating.md

it is not clear where the user is supposed to see the error messages in the table "Common error messages"

**Comment by v-iskha** [comment]
@elqu20 - Hi Elena, please have a look into this.

**Comment by elqu20** [comment]
Investigation is in progress.

**Comment by elqu20** [comment]
The documentation has been updated with the following guidance on accessing error messages: 

To access error messages after attempting an update, SSH into your device after it has rebooted and enter "journalctl -xe -u usb-update" in the PuTTY terminal. This will show all logs from usb-update, from newest to oldest. However, as a first step, we recommend verifying the update by checking the image version with "/etc/adu-version". If the version has not changed, check the usb-update logs for the error messages listed below.
