### ISSUE TITLE
Error: Could not retrieve your IoT Hubs when getting IoT Hubs

### ISSUE THREAD

**Issue by jimbobbennett** [microsoft/Project-Santa-Cruz-Preview#98]
When working through the OOBE, on step 10 when the device is looking for IoT Hubs, instead of finding any hubs, it gives an error and only give the **Create a new Azure IoT Hub** option.

![Screenshot 2021-01-08 142035](https://user-images.githubusercontent.com/1710385/104070877-c2de9280-51bc-11eb-9a2c-22660fe24e96.png)

Even repeated refreshing of the page by going back and forward gives the same error.

The device is successfully connected to the internet, and is able to connect to an existing IoT Edge device when given a connection string.

**Comment by MS-Nikunja** [comment]
Hi @jimbobbennett, could you try again? It generally takes some time to create and activate IoT Hub. There may be a possibility that the IoT Hub was not activated when you were performing OOBE steps.

**Comment by jimbobbennett** [comment]
I'd worked through the steps completely, including configuring the device update service and connecting to AAD, and I could see the IoT Hub in the Azure Portal.

I also have a number of other IoT Hubs that have been around for over a year that it should have detected.

I tried repeatedly over the weekend, and was getting the same issue a few weeks ago when I first tried the setup.

**Comment by SillyKeith** [comment]
Has this flow ever worked for you and shown IoTHubs in OOBE?  Some tenants have a security setting in place that block devices from acting on behalf of users -> They are unable to use "Device Codes".    If you have a second free azure iot account, does it work for that?

**Comment by WendyAnn0079** [comment]
We believe this is due to the account that was used to sign in with.  Working with Jim to fully troubleshoot and resolve the issue.
