### ISSUE TITLE
View stream button in the portal doesn't work

### ISSUE THREAD

**Issue by jimbobbennett** [microsoft/Project-Santa-Cruz-Preview#99]
From the Azure Portal, select the device from the Santa Cruz blade, and try to view the stream by clicking the *View Stream* button.

Nothing happens.

The other 3 buttons on the page work.

There is an info bar about ensuring the device is on the same network, but it is and I can connect using the devices IP address on my WiFi.

![Screenshot 2021-01-08 150510](https://user-images.githubusercontent.com/1710385/104073650-1522b200-51c3-11eb-8525-10f82baaaef1.png)

Looking at the device in the IoT Hub, it doesn't appear to have an edge deployment configuration. This device was set up by creating an IoT Edge device manually and pointing the OOBE set up to it due to #98

**Comment by jimbobbennett** [comment]
Going to close this - it's related to manually creating an edge device and using it due to the Hub detection not working.

**Comment by KStClair72** [comment]
Hi @jimbobbennett , we are reopening this to investigate further.  Thank you.

**Comment by jimbobbennett** [comment]
I don't think this is a bug. I've been having problems with the onboarding detecting my IoT Hubs, so I created an edge device manually in the IoT Hub and used the connection string for the edge device to configure the Santa Cruz device. This edge device didn't have the required edge modules on it, hence why the portal couldn't show the live stream as there was no edge module to service it.

Maybe as an enhancement, when you connect the Santa Cruz device to an existing edge device it should deploy the relevant edge modules automatically, or alert you to what you need to do to configure it yourself.

**Comment by elqu20** [comment]
I didn't manually create an edge device, but I have also been unable to view my device stream through that portal link. The only time I have been able to see the stream was through the link at the end of OOBE (when connected to the SoftAP).

**Comment by v-prsasa** [comment]
Seems the customer got the device into a bad state but was able to resolve the issue. Hence closing the issue.
